# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo
  - conditional_binding_cascade
  - nesting

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
#included:
#  - Pods

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

line_length:
  warning: 200
  error: 200

file_length:
  warning: 700
  error: 1000

identifier_name:
  min_length: 2
